### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by samwilson** [davidstutz/kohana-red#1]
Would you be able to add support for installation via Composer to your modules?

**Comment by davidstutz** [comment]
I will have a look at a basic tutorial - but, yes, I assume it would be possible and beneficial.

**Comment by samwilson** [comment]
Thanks! :) I like the look of these modules. Am investigating integrating them into one of my projects.

**Comment by davidstutz** [comment]
Ok, I admit this was really late, but I was quite busy over the last few month.
